const pokemonTypes = [
  "Normal",
  "Fire",
  "Water",
  "Grass",
  "Electric",
  "Ice",
  "Fighting",
  "Poison",
  "Ground",
  "Flying",
  "Psychic",
  "Bug",
  "Rock",
  "Ghost",
  "Dragon",
  "Steel",
  "Dark",
  "Fairy",
];
const pokemonLocations = [
  // Kanto
  "Viridian Forest",
  "Seafoam Islands",
  "Safari Zone (Kanto)",
  "Power Plant (Kanto)",
  "Cerulean Cave",
  "Pokémon Tower (Lavender Town)",
  "Rock Tunnel",
  "Mt. Moon",

  // Johto
  "Ilex Forest",
  "Whirl Islands",
  "Bell Tower",
  "Burned Tower",
  "Union Cave",
  "Mt. Silver",
  "Lake of Rage",

  // Hoenn
  "Petalburg Woods",
  "Meteor Falls",
  "Granite Cave",
  "Fiery Path",
  "Sky Pillar",
  "Shoal Cave",
  "Safari Zone (Hoenn)",

  // Sinnoh
  "Eterna Forest",
  "Old Chateau",
  "Wayward Cave",
  "Fuego Ironworks",
  "Spear Pillar",
  "Great Marsh",
  "Iron Island",

  // Unova
  "Pinwheel Forest",
  "Chargestone Cave",
  "Relic Castle",
  "Mistralton Cave",
  "Dragonspiral Tower",
  "Giant Chasm",

  // Kalos
  "Santalune Forest",
  "Frost Cavern",
  "Lost Hotel",
  "Friend Safari",
  "Azure Bay",

  // Alola
  "Verdant Cavern",
  "Brooklet Hill",
  "Wela Volcano Park",
  "Mount Lanakila",
  "Poni Wilds",

  // Galar
  "Wild Area",
  "Slumbering Weald",
  "Glimwood Tangle",
  "Crown Tundra",
  "Isle of Armor",

  // Paldea
  "Area Zero",
  "South Province (Area One)",
  "Glaseado Mountain",
  "Asado Desert",
  "Tagtree Thicket",
];
const pokemonItems = [
    "",
    "Potion",
    "Super Potion",
    "Hyper Potion",
    "Max Potion",
    "Revive",
    "Max Revive",
    "Ether",
    "Max Ether",
    "Elixir",
    "Max Elixir",
    "Rare Candy",
    "TM01",
    "TM02",
    "TM03",
    "Everstone",
    "Lucky Egg",
    "Focus Sash",
    "Leftovers",
    "Choice Band",
    "Choice Scarf",
    "Choice Specs",
    "Black Sludge",
    "Sitrus Berry",
    "Chesto Berry",
    "Lum Berry",
    "Wacan Berry",
    "Salac Berry",
    "Haban Berry",
    "Life Orb",
    "Assault Vest",
    "Weakness Policy",
    "Z-Crystal",
    "Band",
    "Shell Bell",
    "Focus Band",
    "Quick Claw",
    "Metronome",
    "King's Rock",
    "Smooth Rock",
    "Heat Rock",
    "Icy Rock",
    "Damp Rock"
];
module.exports = { pokemonTypes, pokemonLocations, pokemonItems };
